sonar.organization=academia-grazi
sonar.projectKey=Shanu7002_academiaGrazi

sonar.sources=lib
sonar.tests=test

sonar.dart.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/*.mocks.dart, **/*.g.dart, **/*.freezed.dart