// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdEYeRzHhh-EDSp69ecZWw1pRpZ69wq_U',
    appId: '1:689931928417:web:d95bed70caae6bbfef3b20',
    messagingSenderId: '689931928417',
    projectId: 'academia-grazi-dev-ab105',
    authDomain: 'academia-grazi-dev-ab105.firebaseapp.com',
    storageBucket: 'academia-grazi-dev-ab105.firebasestorage.app',
    measurementId: 'G-T148B7V287',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCiYFkMB7G6fBa9hlbMrNSVMWsZY0InTg',
    appId: '1:689931928417:android:5855d1bdfd33014fef3b20',
    messagingSenderId: '689931928417',
    projectId: 'academia-grazi-dev-ab105',
    storageBucket: 'academia-grazi-dev-ab105.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN9jVDi3digfOnI_XjjHhb0Xm5drcXtT8',
    appId: '1:689931928417:ios:7f1e173ab226540def3b20',
    messagingSenderId: '689931928417',
    projectId: 'academia-grazi-dev-ab105',
    storageBucket: 'academia-grazi-dev-ab105.firebasestorage.app',
    iosBundleId: 'com.example.academiagrazi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN9jVDi3digfOnI_XjjHhb0Xm5drcXtT8',
    appId: '1:689931928417:ios:7f1e173ab226540def3b20',
    messagingSenderId: '689931928417',
    projectId: 'academia-grazi-dev-ab105',
    storageBucket: 'academia-grazi-dev-ab105.firebasestorage.app',
    iosBundleId: 'com.example.academiagrazi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdEYeRzHhh-EDSp69ecZWw1pRpZ69wq_U',
    appId: '1:689931928417:web:19af417441550f42ef3b20',
    messagingSenderId: '689931928417',
    projectId: 'academia-grazi-dev-ab105',
    authDomain: 'academia-grazi-dev-ab105.firebaseapp.com',
    storageBucket: 'academia-grazi-dev-ab105.firebasestorage.app',
    measurementId: 'G-V4MXV9S9WM',
  );
}
